#' Read Acute extract
#'
#' @param year Year of BOXI extract
#'
#' @return csv data file for Acute
#' @export
#'
read_extract_acute <- function(year) {
  extract_acute_path <- get_boxi_extract_path(year = year, type = "Acute")

  # Read BOXI extract
  extract_acute <- readr::read_csv(extract_acute_path,
    col_type = cols(
      "Costs Financial Year (01)" = col_integer(),
      "Costs Financial Month Number (01)" = col_double(),
      "GLS Record" = col_character(),
      "Date of Admission(01)" = col_date(format = "%Y/%m/%d %T"),
      "Date of Discharge(01)" = col_date(format = "%Y/%m/%d %T"),
      "Pat UPI" = col_character(),
      "Pat Gender Code" = col_double(),
      "Pat Date Of Birth [C]" = col_date(format = "%Y/%m/%d %T"),
      "Practice Location Code" = col_character(),
      "Practice NHS Board Code - current" = col_character(),
      "Geo Postcode [C]" = col_character(),
      "NHS Board of Residence Code - current" = col_character(),
      "Geo Council Area Code" = col_character(),
      "Geo HSCP of Residence Code - current" = col_character(),
      "Geo Data Zone 2011" = col_character(),
      "Treatment Location Code" = col_character(),
      "Treatment NHS Board Code - current" = col_character(),
      "Occupied Bed Days (01)" = col_double(),
      "Inpatient Day Case Identifier Code" = col_character(),
      "Specialty Classificat. 1/4/97 Code" = col_character(),
      "Significant Facility Code" = col_character(),
      "Lead Consultant/HCP Code" = col_character(),
      "Management of Patient Code" = col_character(),
      "Patient Category Code" = col_character(),
      "Admission Type Code" = col_character(),
      "Admitted Trans From Code" = col_character(),
      "Location Admitted Trans From Code" = col_character(),
      "Old SMR1 Type of Admission Code" = col_integer(),
      "Discharge Type Code" = col_character(),
      "Discharge Trans To Code" = col_character(),
      "Location Discharged Trans To Code" = col_character(),
      "Diagnosis 1 Code (6 char)" = col_character(),
      "Diagnosis 2 Code (6 char)" = col_character(),
      "Diagnosis 3 Code (6 char)" = col_character(),
      "Diagnosis 4 Code (6 char)" = col_character(),
      "Diagnosis 5 Code (6 char)" = col_character(),
      "Diagnosis 6 Code (6 char)" = col_character(),
      "Operation 1A Code (4 char)" = col_character(),
      "Operation 1B Code (4 char)" = col_character(),
      "Date of Operation 1 (01)" = col_date(format = "%Y/%m/%d %T"),
      "Operation 2A Code (4 char)" = col_character(),
      "Operation 2B Code (4 char)" = col_character(),
      "Date of Operation 2 (01)" = col_date(format = "%Y/%m/%d %T"),
      "Operation 3A Code (4 char)" = col_character(),
      "Operation 3B Code (4 char)" = col_character(),
      "Date of Operation 3 (01)" = col_date(format = "%Y/%m/%d %T"),
      "Operation 4A Code (4 char)" = col_character(),
      "Operation 4B Code (4 char)" = col_character(),
      "Date of Operation 4 (01)" = col_date(format = "%Y/%m/%d %T"),
      "Age at Midpoint of Financial Year (01)" = col_integer(),
      "Continuous Inpatient Stay(SMR01) (inc GLS)" = col_integer(),
      "Continuous Inpatient Journey Marker (01)" = col_character(),
      "CIJ Planned Admission Code (01)" = col_integer(),
      "CIJ Inpatient Day Case Identifier Code (01)" = col_character(),
      "CIJ Type of Admission Code (01)" = col_character(),
      "CIJ Admission Specialty Code (01)" = col_character(),
      "CIJ Discharge Specialty Code (01)" = col_character(),
      "CIJ Start Date (01)" = col_date(format = "%Y/%m/%d %T"),
      "CIJ End Date (01)" = col_date(format = "%Y/%m/%d %T"),
      "Total Net Costs (01)" = col_double(),
      "NHS Hospital Flag (01)" = col_character(),
      "Community Hospital Flag (01)" = col_character(),
      "Alcohol Related Admission (01)" = col_character(),
      "Substance Misuse Related Admission (01)" = col_character(),
      "Falls Related Admission (01)" = col_character(),
      "Self Harm Related Admission (01)" = col_character(),
      "Unique Record Identifier" = col_character(),
      "Line Number (01)" = col_character()
    )
  ) %>%
    # Rename variables
    dplyr::rename(
      tadm = "Admission Type Code",
      adtf = "Admitted Trans From Code",
      age = "Age at Midpoint of Financial Year (01)",
      alcohol_adm = "Alcohol Related Admission (01)",
      cij_adm_spec = "CIJ Admission Specialty Code (01)",
      cij_dis_spec = "CIJ Discharge Specialty Code (01)",
      cij_end_date = "CIJ End Date (01)",
      cij_pattype_code = "CIJ Planned Admission Code (01)",
      cij_start_date = "CIJ Start Date (01)",
      cij_admtype = "CIJ Type of Admission Code (01)",
      commhosp = "Community Hospital Flag (01)",
      cij_marker = "Continuous Inpatient Journey Marker (01)",
      smr01_cis_marker = "Continuous Inpatient Stay(SMR01) (inc GLS)",
      costmonthnum = "Costs Financial Month Number (01)",
      costsfy = "Costs Financial Year (01)",
      diag1 = "Diagnosis 1 Code (6 char)",
      diag2 = "Diagnosis 2 Code (6 char)",
      diag3 = "Diagnosis 3 Code (6 char)",
      diag4 = "Diagnosis 4 Code (6 char)",
      diag5 = "Diagnosis 5 Code (6 char)",
      diag6 = "Diagnosis 6 Code (6 char)",
      dischto = "Discharge Trans To Code",
      disch = "Discharge Type Code",
      falls_adm = "Falls Related Admission (01)",
      lca = "Geo Council Area Code",
      DataZone = "Geo Data Zone 2011",
      postcode = "Geo Postcode [C]",
      HSCP = "Geo HSCP of Residence Code - current",
      conc = "Lead Consultant/HCP Code",
      admloc = "Location Admitted Trans From Code",
      dischloc = "Location Discharged Trans To Code",
      mpat = "Management of Patient Code",
      hbrescode = "NHS Board of Residence Code - current",
      nhshosp = "NHS Hospital Flag (01)",
      yearstay = "Occupied Bed Days (01)",
      oldtadm = "Old SMR1 Type of Admission Code",
      op1a = "Operation 1A Code (4 char)",
      op1b = "Operation 1B Code (4 char)",
      op2a = "Operation 2A Code (4 char)",
      op2b = "Operation 2B Code (4 char)",
      op3a = "Operation 3A Code (4 char)",
      op3b = "Operation 3B Code (4 char)",
      op4a = "Operation 4A Code (4 char)",
      op4b = "Operation 4B Code (4 char)",
      gender = "Pat Gender Code",
      chi = "Pat UPI",
      cat = "Patient Category Code",
      gpprac = "Practice Location Code",
      hbpraccode = "Practice NHS Board Code - current",
      selfharm_adm = "Self Harm Related Admission (01)",
      sigfac = "Significant Facility Code",
      spec = "Specialty Classificat. 1/4/97 Code",
      submis_adm = "Substance Misuse Related Admission (01)",
      cost_total_net = "Total Net Costs (01)",
      location = "Treatment Location Code",
      hbtreatcode = "Treatment NHS Board Code - current",
      uri = "Unique Record Identifier",
      record_keydate1 = "Date of Admission(01)",
      record_keydate2 = "Date of Discharge(01)",
      dateop1 = "Date of Operation 1 (01)",
      dateop2 = "Date of Operation 2 (01)",
      dateop3 = "Date of Operation 3 (01)",
      dateop4 = "Date of Operation 4 (01)",
      dob = "Pat Date Of Birth [C]",
      ipdc = "Inpatient Day Case Identifier Code",
      cij_ipdc = "CIJ Inpatient Day Case Identifier Code (01)",
      lineno = "Line Number (01)",
      GLS_record = "GLS Record"
    )

  return(extract_acute)
}
