#' Read Maternity extract
#'
#' @inherit read_extract_acute
#'
#' @export
read_extract_maternity <- function(
  year,
  file_path = get_boxi_extract_path(year = year, type = "maternity")
) {
  log_slf_event(stage = "read", status = "start", type = "maternity", year = year)

  # Read BOXI extract
  extract_maternity <- read_file(file_path,
    col_type = readr::cols(
      "Costs Financial Year" = readr::col_double(),
      "Date of Admission Full Date" = readr::col_date(format = "%Y/%m/%d %T"),
      "Date of Discharge Full Date" = readr::col_date(format = "%Y/%m/%d %T"),
      "anon_chi" = readr::col_character(),
      "Pat Date Of Birth [C]" = readr::col_date(format = "%Y/%m/%d %T"),
      "Practice Location Code" = readr::col_character(),
      "Practice NHS Board Code - current" = readr::col_character(),
      "Geo Postcode [C]" = readr::col_character(),
      "NHS Board of Residence Code - current" = readr::col_character(),
      "HSCP of Residence Code - current" = readr::col_character(),
      "Geo Council Area Code" = readr::col_character(),
      "Treatment Location Code" = readr::col_character(),
      "Treatment NHS Board Code - current" = readr::col_character(),
      "Occupied Bed Days" = readr::col_double(),
      "Specialty Classification 1/4/97 Code" = readr::col_character(),
      "Significant Facility Code" = readr::col_character(),
      "Consultant/HCP Code" = readr::col_character(),
      "Management of Patient Code" = readr::col_character(),
      "Admission Reason Code" = readr::col_character(),
      "Admitted/Transfer from Code (new)" = readr::col_character(),
      "Admitted/transfer from - Location Code" = readr::col_character(),
      "Discharge Type Code" = readr::col_character(),
      "Discharge/Transfer to Code (new)" = readr::col_character(),
      "Discharged to - Location Code" = readr::col_character(),
      "Condition On Discharge Code" = readr::col_double(),
      "Continuous Inpatient Journey Marker" = readr::col_double(),
      "CIJ Planned Admission Code" = readr::col_double(),
      "CIJ Inpatient Day Case Identifier Code" = readr::col_character(),
      "CIJ Type of Admission Code" = readr::col_character(),
      "CIJ Admission Specialty Code" = readr::col_character(),
      "CIJ Discharge Specialty Code" = readr::col_character(),
      "CIJ Start Date" = readr::col_date(format = "%Y/%m/%d %T"),
      "CIJ End Date" = readr::col_date(format = "%Y/%m/%d %T"),
      "Total Net Costs" = readr::col_double(),
      "Diagnosis 1 Discharge Code" = readr::col_character(),
      "Diagnosis 2 Discharge Code" = readr::col_character(),
      "Diagnosis 3 Discharge Code" = readr::col_character(),
      "Diagnosis 4 Discharge Code" = readr::col_character(),
      "Diagnosis 5 Discharge Code" = readr::col_character(),
      "Diagnosis 6 Discharge Code" = readr::col_character(),
      "Operation 1A Code" = readr::col_character(),
      "Operation 2A Code" = readr::col_character(),
      "Operation 3A Code" = readr::col_character(),
      "Operation 4A Code" = readr::col_character(),
      "Date of Main Operation Full Date" = readr::col_date(format = "%Y/%m/%d %T"),
      "Age at Midpoint of Financial Year" = readr::col_double(),
      "NHS Hospital Flag" = readr::col_character(),
      "Community Hospital Flag" = readr::col_character(),
      "Alcohol Related AdmissioN" = readr::col_character(),
      "Substance Misuse Related Admission" = readr::col_character(),
      "Falls Related Admission" = readr::col_character(),
      "Self Harm Related Admission" = readr::col_character(),
      "Maternity Unique Record Identifier [C]" = readr::col_character()
    )
  ) %>%
    # Rename variables in line with SLF variable names
    dplyr::rename(
      adtf = "Admitted/Transfer from Code (new)",
      admloc = "Admitted/transfer from - Location Code",
      record_keydate1 = "Date of Admission Full Date",
      record_keydate2 = "Date of Discharge Full Date",
      dateop1 = "Date of Main Operation Full Date",
      dob = "Pat Date Of Birth [C]",
      age = "Age at Midpoint of Financial Year",
      alcohol_adm = "Alcohol Related AdmissioN",
      cij_adm_spec = "CIJ Admission Specialty Code",
      cij_dis_spec = "CIJ Discharge Specialty Code",
      cij_end_date = "CIJ End Date",
      cij_pattype_code = "CIJ Planned Admission Code",
      cij_ipdc = "CIJ Inpatient Day Case Identifier Code",
      cij_start_date = "CIJ Start Date",
      cij_admtype = "CIJ Type of Admission Code",
      commhosp = "Community Hospital Flag",
      discondition = "Condition On Discharge Code",
      conc = "Consultant/HCP Code",
      cij_marker = "Continuous Inpatient Journey Marker",
      costsfy = "Costs Financial Year",
      diag1 = "Diagnosis 1 Discharge Code",
      diag2 = "Diagnosis 2 Discharge Code",
      diag3 = "Diagnosis 3 Discharge Code",
      diag4 = "Diagnosis 4 Discharge Code",
      diag5 = "Diagnosis 5 Discharge Code",
      diag6 = "Diagnosis 6 Discharge Code",
      dischto = "Discharge/Transfer to Code (new)",
      disch = "Discharge Type Code",
      dischloc = "Discharged to - Location Code",
      falls_adm = "Falls Related Admission",
      lca = "Geo Council Area Code",
      postcode = "Geo Postcode [C]",
      mpat = "Management of Patient Code",
      hbrescode = "NHS Board of Residence Code - current",
      hscp = "HSCP of Residence Code - current",
      nhshosp = "NHS Hospital Flag",
      yearstay = "Occupied Bed Days",
      op1a = "Operation 1A Code",
      op2a = "Operation 2A Code",
      op3a = "Operation 3A Code",
      op4a = "Operation 4A Code",
      anon_chi = "anon_chi",
      gpprac = "Practice Location Code",
      hbpraccode = "Practice NHS Board Code - current",
      selfharm_adm = "Self Harm Related Admission",
      sigfac = "Significant Facility Code",
      spec = "Specialty Classification 1/4/97 Code",
      submis_adm = "Substance Misuse Related Admission",
      cost_total_net = "Total Net Costs",
      location = "Treatment Location Code",
      hbtreatcode = "Treatment NHS Board Code - current",
      uri = "Maternity Unique Record Identifier [C]"
    )

  log_slf_event(stage = "read", status = "complete", type = "maternity", year = year)

  return(extract_maternity)
}
