# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
 pull_request:
  branches: [main-R]

name: Check

jobs:
 document-style:
  name: Document and style
  runs-on: ubuntu-latest
  env:
   GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  steps:
   - uses: actions/checkout@v3

   - uses: r-lib/actions/pr-fetch@v2
     with:
      repo-token: ${{ secrets.GITHUB_TOKEN }}

   - uses: r-lib/actions/setup-r@v2
     with:
      use-public-rspm: true

   - uses: r-lib/actions/setup-r-dependencies@v2
     with:
      extra-packages: roxygen2, styler

   - name: Document
     run: Rscript -e 'roxygen2::roxygenise()'

   - uses: stefanzweifel/git-auto-commit-action@v4
     with:
      commit_message: Document with {roxygen2} (GitHub action)
      file_pattern: man/* NAMESPACE

   - name: Style package functions
     run: Rscript -e 'styler::style_pkg()'

   - name: Style production scripts
     run: Rscript -e 'styler::style_dir("Production_scripts/")'

   - name: Style other scripts
     run: Rscript -e 'styler::style_dir("Make_R_files/")'

   - uses: stefanzweifel/git-auto-commit-action@v4
     with:
      commit_message: Style with {styler} (GitHub action)

 lint:
  needs: document-style
  runs-on: ubuntu-latest
  env:
   GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  steps:
   - uses: actions/checkout@v3

   - uses: r-lib/actions/setup-r@v2
     with:
      use-public-rspm: true

   - uses: r-lib/actions/setup-r-dependencies@v2
     with:
      extra-packages: lintr

   - name: Lint
     run: lintr::lint_package()
     shell: Rscript {0}
